version: 1

secret:
  ignore-paths:
    - "**/*.md"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/*.min.js"
    - "**/dist/**"
    - "**/build/**"
    - "**/node_modules/**"
    - "**/.next/**"
    - "**/coverage/**"
    - "**/*.log"

  ignore-matches:
    - name: "Ignore test email"
      match: "hocvu2003@gmail\\.com"

    - name: "Ignore test password masked pattern"
      match: "h.{3,}u"

    - name: "Ignore raw password"
      match: "h.*u"
