# GitGuardian Configuration
# This file configures how GitGuardian scans your repository for secrets

# Version
version: 2

# File patterns to exclude from scanning
paths-ignore:
  - "**/*.md"              # Markdown files
  - "**/package-lock.json" # Lock files
  - "**/yarn.lock"         # Yarn lock
  - "**/*.min.js"          # Minified JS
  - "**/dist/**"           # Build output
  - "**/build/**"          # Build output
  - "**/node_modules/**"   # Dependencies
  - "**/.next/**"          # Next.js build
  - "**/coverage/**"       # Test coverage
  - "**/*.log"             # Log files

# Specific secrets to ignore (use with caution)
matches-ignore:
  - name: "Test secrets in test files"
    match: test_.*_key
  - name: "Example values in documentation"
    match: "example.*"
